modules/fflibe/main/default/objects/fflibe_DomainMapping__mdt/fflibe_DomainMapping__mdt.object-meta.xml
<CustomObject>
    <description>Maps SObjects and Objects to the Apex Domain class implementing fflib_SObjectDomain</description>
    <label>Domain Mapping</label>
    <pluralLabel>Domain Mappings</pluralLabel>
</CustomObject>

modules/fflibe/main/default/objects/fflibe_DomainMapping__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <inlineHelpText>Implementing fflib_SObjectDomain</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

modules/fflibe/main/default/objects/fflibe_DomainMapping__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <inlineHelpText>API Name of the SObject</inlineHelpText>
    <label>SObject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

modules/fflibe/main/default/objects/fflibe_SelectorMapping__mdt/fflibe_SelectorMapping__mdt.object-meta.xml
<CustomObject>
    <description>maps an SObjectType to the Selector apex class</description>
    <label>Selector Mapping</label>
    <pluralLabel>Selector Mappings</pluralLabel>
</CustomObject>

modules/fflibe/main/default/objects/fflibe_SelectorMapping__mdt/fields/SelectorClass__c.field-meta.xml
<CustomField>
    <fullName>SelectorClass__c</fullName>
    <inlineHelpText>Exact name of the apex selector class implementing fflib_ISObjectSelector</inlineHelpText>
    <label>Selector Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

modules/fflibe/main/default/objects/fflibe_SelectorMapping__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <inlineHelpText>API Name of the SObject</inlineHelpText>
    <label>SObjectType</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

modules/fflibe/main/default/classes/fflibe_Application.cls
public inherited sharing virtual class fflibe_Application extends fflib_Application {
    
    // This version of ServiceFactory does not maintain an interface mapping, only a mock class mapping.
    // This way, we don't have to maintain an interface mapping and can immediately create a new service class.
    public virtual class ServiceFactory extends fflib_Application.ServiceFactory {

        public ServiceFactory() {
            m_serviceInterfaceTypeByMockService = new Map<Type,Object>();
        }
        
        public virtual override Object newInstance(Type serviceType) {
            if(m_serviceInterfaceTypeByMockService.containsKey(serviceType))
				return m_serviceInterfaceTypeByMockService.get(serviceType);

            // don't check interface mapping, since we are expecting the exact type of class
            return serviceType.newInstance();
        }

    }

    public virtual class SelectorFactory extends fflib_Application.SelectorFactory {

        // private Map<String, String> sObjectNameToClassNameMappings;

        // instead of defining the mapping in an Application class, it is defined in custom metadata
        // so that when multiple developers are working, they are not constantly editing the same
        // application class
        public SelectorFactory() {
            super(new Map<SObjectType, Type>());
            for (fflibe_SelectorMapping__mdt mapping : fflibe_MetadataHelper.getSelectorMappings()) {
                try {
                    SObjectType sObjType = ((SObject)Type.forName('Schema.' + mapping.SObjectType__c).newInstance()).getSObjectType();
                    Type classType = Type.forName(mapping.SelectorClass__c);
                    this.m_sObjectBySelectorType.put(sObjType, classType);
                } catch (Exception e) {
                    lgr_Logger.log(e, 'fflibe_Application', 'SelectorFactory init', 'selector mapping: ' + mapping);
                    throw e;
                }
            }
        }

    }

    public virtual class DomainFactory extends fflib_Application.DomainFactory {

        public DomainFactory() {
            super(fflibe_APP.SELECTOR, new Map<SObjectType, Type>());
        }

        protected virtual override Map<Object, Type> getConstructorTypeByObject(Map<SObjectType, Type> constructorTypeBySObjectType)
		{
			Map<Object, Type> result = new Map<Object, Type>();
			for (fflibe_DomainMapping__mdt mapping : fflibe_MetadataHelper.getDomainMappings()) {
                try {
                    SObjectType sObjType = ((SObject)Type.forName('Schema.' + mapping.SObject__c).newInstance()).getSObjectType();
                    result.put(
                            (Object) sObjType,
                            Type.forName(mapping.ApexClass__c + '.Constructor')
                    );
                } catch (Exception e) {
                    lgr_Logger.log(e, 'fflibe_Application', 'DomainFactory init', 'domain mapping: ' + mapping);
                    throw e;
                }
			}
			return result;
		}

    }

}