modules/fflibe/main/default/objects/fflibe_DomainMapping__mdt/fflibe_DomainMapping__mdt.object-meta.xml
<CustomObject>
    <description>Maps SObjects and Objects to the Apex Domain class implementing fflib_SObjectDomain</description>
    <label>Domain Mapping</label>
    <pluralLabel>Domain Mappings</pluralLabel>
</CustomObject>

modules/fflibe/main/default/objects/fflibe_DomainMapping__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <inlineHelpText>Implementing fflib_SObjectDomain</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

modules/fflibe/main/default/objects/fflibe_DomainMapping__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <inlineHelpText>API Name of the SObject</inlineHelpText>
    <label>SObject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

modules/fflibe/main/default/objects/fflibe_SelectorMapping__mdt/fflibe_SelectorMapping__mdt.object-meta.xml
<CustomObject>
    <description>maps an SObjectType to the Selector apex class</description>
    <label>Selector Mapping</label>
    <pluralLabel>Selector Mappings</pluralLabel>
</CustomObject>

modules/fflibe/main/default/objects/fflibe_SelectorMapping__mdt/fields/SelectorClass__c.field-meta.xml
<CustomField>
    <fullName>SelectorClass__c</fullName>
    <inlineHelpText>Exact name of the apex selector class implementing fflib_ISObjectSelector</inlineHelpText>
    <label>Selector Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

modules/fflibe/main/default/objects/fflibe_SelectorMapping__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <inlineHelpText>API Name of the SObject</inlineHelpText>
    <label>SObjectType</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

modules/fflibe/main/default/classes/fflibe_MetadataHelper.cls
// Purpose of this class is so that custom metadata can easily be mocked
public inherited sharing class fflibe_MetadataHelper {

    @TestVisible
    private static Boolean returnMockData = false;

    public static fflibe_SelectorMapping__mdt[] getSelectorMappings() {
        return (Test.isRunningTest() && returnMockData) 
            ? new fflibe_SelectorMapping__mdt[] {
                new fflibe_SelectorMapping__mdt(SObjectType__c = 'Account', SelectorClass__c = 'fflibe_TESTSelector1', DeveloperName = 'Account'),
                new fflibe_SelectorMapping__mdt(SObjectType__c = 'Contact', SelectorClass__c = 'fflibe_TESTSelector2', DeveloperName = 'Contact')
            }
            : fflibe_SelectorMapping__mdt.getAll().values();
    }

    public static fflibe_DomainMapping__mdt[] getDomainMappings() {
        return (Test.isRunningTest() && returnMockData) 
            ? new fflibe_DomainMapping__mdt[] {
                new fflibe_DomainMapping__mdt(SObject__c = 'Account', ApexClass__c = 'fflibe_TESTDomain1', DeveloperName = 'Account'),
                new fflibe_DomainMapping__mdt(SObject__c = 'Contact', ApexClass__c = 'fflibe_TESTDomain2', DeveloperName = 'Contact')
            }
            : fflibe_DomainMapping__mdt.getAll().values();
    }

}