modules/api/main/default/objects/api_LogEvent__e/api_LogEvent__e.object-meta.xml
<CustomObject>
    <label>API Log Event</label>
    <pluralLabel>API Log Events</pluralLabel>
</CustomObject>

modules/api/main/default/objects/api_LogEvent__e/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

modules/api/main/default/objects/api_LogEvent__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

modules/api/main/default/objects/api_LogEvent__e/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <defaultValue>&apos;GET&apos;</defaultValue>
    <label>Method</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

modules/api/main/default/objects/api_LogEvent__e/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

modules/api/main/default/objects/api_LogEvent__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

modules/api/main/default/objects/api_LogEvent__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;DEBUG&apos;</defaultValue>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

modules/api/main/default/objects/api_LogLevels__c/api_LogLevels__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>API Log Levels</label>
</CustomObject>

modules/api/main/default/objects/api_LogLevels__c/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>1-9</inlineHelpText>
    <label>LogLevel</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

modules/api/main/default/classes/Api_RequestService.cls
public inherited sharing class Api_RequestService {

  public static final Api_RequestService INSTANCE = (Api_RequestService)fflibe_APP.SERVICE.newInstance(Api_RequestService.class);

  public String handleRequest(String handlerClassName, RestRequest req, RestResponse res) {
    try {
      Integer logLevel = Integer.valueOf(api_LogLevels__c.getInstance(UserInfo.getUserId()).LogLevel__c) ?? 1;

      api_IRequestHandler handler = (api_IRequestHandler)Type.forName(handlerClassName).newInstance();

      String handlerRes = handler.handleRequest(req, res);

      if (logLevel > 1) {
        // publish event to not accrue more dml
        api_LogEvent__e logEvent = new api_LogEvent__e(
          Body__c = req.requestBody.toString(),
          Method__c = req.httpMethod,
          Params__c = JSON.serialize(getRequestParams(req)),
          Message__c = 'SUCCESS',
          Type__c = 'DEBUG'
        );
        EventBus.publish(logEvent);
      }

      return handlerRes;

    } catch (Exception err) {
      // publish an event immediately so that we can log while still throwing the error
      api_LogEvent__e logEvent = new api_LogEvent__e(
        Body__c = req.requestBody.toString(),
        Method__c = req.httpMethod,
        Params__c = JSON.serialize(getRequestParams(req)),
        StackTrace__c = err.getStackTraceString(),
        Message__c = err.getMessage(),
        Type__c = 'ERROR'
      );
      EventBus.publish(logEvent);

      throw err;
    }
  }

  private Map<String, String> getRequestParams(RestRequest req) {
    Map<String,String> res = new Map<String, String>();
    for (String key : req.params.keySet()) {
      res.put(key, req.params.get(key));
    }
    return res;
  }

}