modules/lgr/main/default/objects/lgr_Log__c/lgr_Log__c.object-meta.xml
<CustomObject>
    <description>create records of this type in apex or other process when wanting to store error messages or info in the database</description>
    <label>Custom Log</label>
    <nameField>
        <displayFormat>CL-{0000000}</displayFormat>
        <label>Custom Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

modules/lgr/main/default/objects/lgr_Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <defaultValue>&apos;DEBUG&apos;</defaultValue>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CRITICAL</fullName>
            </value>
            <value>
                <fullName>WARNING</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

modules/lgr/main/default/objects/lgr_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Exception Message or Info Message. Says what went wrong or what is happening.</description>
    <inlineHelpText>Exception Message or Info Message. Says what went wrong or what is happening.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

modules/lgr/main/default/objects/lgr_Log__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>any additional data/parameters that would be helpful to have</description>
    <inlineHelpText>any additional data/parameters that would be helpful to have (e.g. failing record id)</inlineHelpText>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

modules/lgr/main/default/objects/lgr_Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>where in the code this log occurred</description>
    <inlineHelpText>where in the code this log occurred (retrieved from exception.getStackTraceString() for exceptions)</inlineHelpText>
    <label>Stack Trace</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/lgr_LogEvent__e.object-meta.xml
<CustomObject>
    <description>This maps to a lgr_Log__c record from a Platform-Event Triggered Flow. Useful when catching an error in Apex, logging the error by immediately publishing this event, and then re-throwing the error.</description>
    <label>Custom Log Event</label>
    <pluralLabel>Custom Log Events</pluralLabel>
</CustomObject>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>=&gt; lgr_Log__c.Class__c</description>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <defaultValue>&apos;DEBUG&apos;</defaultValue>
    <description>=&gt; lgr_Log__c.Level__c</description>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>=&gt; lgr_Log__c.Message__c</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>=&gt; lgr_Log__c.Method__c</description>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/Occured__c.field-meta.xml
<CustomField>
    <fullName>Occured__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>=&gt; lgr_Log__c.Occured__c</description>
    <label>Occured</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>=&gt; lgr_Log__c.Parameters__c</description>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/Save__c.field-meta.xml
<CustomField>
    <fullName>Save__c</fullName>
    <defaultValue>false</defaultValue>
    <description>=&gt; lgr_Log__c.Save__c</description>
    <label>Save</label>
    <type>Checkbox</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>=&gt; lgr_Log__c.StackTrace__c</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogLevels__c/lgr_LogLevels__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Control the level of logs created for each apex class / process. Each field api name should be the exact name of a class. It should be a text field with one of these values: CRITICAL, WARNING, INFO, DEBUG.</description>
    <label>Custom Log Levels</label>
</CustomObject>

modules/lgr/main/default/classes/lgr_Logger.cls
public without sharing class lgr_Logger {
    
    public enum LogLevel { // IN ORDER!
        CRITICAL, WARNING, INFO, DEBUG
    }

    // PUBLIC METHODS

    public static void log(String className, String methodName, String message, String parameters, String stackTrace, LogLevel level) {
        if (validateLogLevelSettings(className, level)) { 
            createLog(className, methodName, parameters, stackTrace, message, level); 
        }
    }

    public static void log(Exception e, String className, String methodName, String parameters) {
        logImmediately(className, methodName, e.getMessage(), parameters, e.getStackTraceString(), LogLevel.CRITICAL);
    }

    public static void logImmediately(String className, String methodName, String message, String parameters, String stackTrace, LogLevel level) {
        if (validateLogLevelSettings(className, level)) {
            lgr_LogEvent__e e = new lgr_LogEvent__e(
                Class__c = className,
                Level__c = level.name(),
                Message__c = message,
                Method__c = methodName,
                Occured__c = DateTime.now(),
                Parameters__c = parameters,
                Save__c = false,
                StackTrace__c = stackTrace
            );
            EventBus.publish(e);
        }
    }


    // PRIVATE METHODS

    // Determines if log record should be created based on lgr_LogLevels__c custom setting.
    // If no setting is found, only validate if it is a CRITICAL Log Level.
    private static Boolean validateLogLevelSettings(String className, LogLevel level) {
        String fieldName = className + '__c';
        try {
            String setting = (String)lgr_LogLevels__c.getInstance(UserInfo.getUserId()).get(fieldName);
            return level.ordinal() <= LogLevel.valueOf(setting).ordinal();
        } catch (Exception e) {
            return level == LogLevel.CRITICAL;
        }
    }

    private static void createLog(String className, String methodName, String parameters, String stackTrace, String message, LogLevel level) {
        lgr_Log__c log = new lgr_Log__c(
            Class__c = className,
            Method__c = methodName,
            Message__c = message,
            StackTrace__c = stackTrace,
            Parameters__c = parameters,
            Level__c = level.name(),
            Occured__c = System.now()
        );
        if (!System.isBatch() && !System.isFuture()) {
            insertLogFuture(JSON.serialize(log));
        } else {
            handleLogInsert(log);
        }
    }

    @TestVisible
    private static void handleLogInsert(lgr_Log__c log) {
        try {
            insert log;
        } catch (Exception e) {
            System.debug('failed to insert custom log because of exception: ' + e.getMessage() + ', ' + e.getStackTraceString());
        }
    }

    @future
    private static void insertLogFuture(String jsonLog) {
        lgr_Log__c log = (lgr_Log__c)JSON.deserialize(jsonLog, lgr_Log__c.class);
        handleLogInsert(log);
    }

}