modules/lgr/main/default/objects/lgr_Log__c/lgr_Log__c.object-meta.xml
<CustomObject>
    <description>create records of this type in apex or other process when wanting to store error messages or info in the database</description>
    <label>Custom Log</label>
    <nameField>
        <displayFormat>CL-{0000000}</displayFormat>
        <label>Custom Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

modules/lgr/main/default/objects/lgr_LogSettings__c/lgr_LogSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Custom Log Settings</label>
</CustomObject>

modules/lgr/main/default/objects/lgr_LogSettings__c/fields/LogLifetimeInMonths__c.field-meta.xml
<CustomField>
    <fullName>LogLifetimeInMonths__c</fullName>
    <defaultValue>3</defaultValue>
    <inlineHelpText>How many months should unsaved logs stick around before deleted in a monthly batch job?</inlineHelpText>
    <label>LogLifetimeInMonths</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

modules/lgr/main/default/classes/lgr_LogDeletionJob.cls
public without sharing class lgr_LogDeletionJob implements Database.Batchable<SObject> {
    
    // query all records where Save__c is not true and that occur before the date given in constructor
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Integer lifetimeInMonths = Integer.valueOf(lgr_LogSettings__c.getInstance(UserInfo.getUserId()).LogLifetimeInMonths__c);
        return Database.getQueryLocator('SELECT Id FROM lgr_Log__c WHERE Save__c != TRUE AND Occured__c < LAST_N_MONTHS:' + lifetimeInMonths);
    }

    public void execute(Database.BatchableContext bc, sObject[] logs) {
        delete logs;
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('Finished CustomLogDeletionJob');
    }
}