modules/lgr/main/default/objects/lgr_Log__c/lgr_Log__c.object-meta.xml
<CustomObject>
    <description>create records of this type in apex or other process when wanting to store error messages or info in the database</description>
    <label>Custom Log</label>
    <nameField>
        <displayFormat>CL-{0000000}</displayFormat>
        <label>Custom Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

modules/lgr/main/default/objects/lgr_Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <defaultValue>&apos;DEBUG&apos;</defaultValue>
    <label>Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CRITICAL</fullName>
            </value>
            <value>
                <fullName>WARNING</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

modules/lgr/main/default/objects/lgr_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Exception Message or Info Message. Says what went wrong or what is happening.</description>
    <inlineHelpText>Exception Message or Info Message. Says what went wrong or what is happening.</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

modules/lgr/main/default/objects/lgr_Log__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>any additional data/parameters that would be helpful to have</description>
    <inlineHelpText>any additional data/parameters that would be helpful to have (e.g. failing record id)</inlineHelpText>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

modules/lgr/main/default/objects/lgr_Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>where in the code this log occurred</description>
    <inlineHelpText>where in the code this log occurred (retrieved from exception.getStackTraceString() for exceptions)</inlineHelpText>
    <label>Stack Trace</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/lgr_LogEvent__e.object-meta.xml
<CustomObject>
    <description>This maps to a lgr_Log__c record from a Platform-Event Triggered Flow. Useful when catching an error in Apex, logging the error by immediately publishing this event, and then re-throwing the error.</description>
    <label>Custom Log Event</label>
    <pluralLabel>Custom Log Events</pluralLabel>
</CustomObject>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>=&gt; lgr_Log__c.Class__c</description>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <defaultValue>&apos;DEBUG&apos;</defaultValue>
    <description>=&gt; lgr_Log__c.Level__c</description>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>=&gt; lgr_Log__c.Message__c</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>=&gt; lgr_Log__c.Method__c</description>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/Occured__c.field-meta.xml
<CustomField>
    <fullName>Occured__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>=&gt; lgr_Log__c.Occured__c</description>
    <label>Occured</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <description>=&gt; lgr_Log__c.Parameters__c</description>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogEvent__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>=&gt; lgr_Log__c.StackTrace__c</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogLevels__c/lgr_LogLevels__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Control the level of logs created for each apex class / process. Each field api name should be the exact name of a class. It should be a text field with one of these values: CRITICAL, WARNING, INFO, DEBUG.</description>
    <label>Custom Log Levels</label>
</CustomObject>

modules/lgr/main/default/objects/lgr_LogLevels__c/fields/ZZZ_TEST_C__c.field-meta.xml
<CustomField>
    <fullName>ZZZ_TEST_C__c</fullName>
    <defaultValue>&apos;CRITICAL&apos;</defaultValue>
    <label>ZZZ_TEST_C</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogLevels__c/fields/ZZZ_TEST_D__c.field-meta.xml
<CustomField>
    <fullName>ZZZ_TEST_D__c</fullName>
    <defaultValue>&apos;DEBUG&apos;</defaultValue>
    <label>ZZZ_TEST_D</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogLevels__c/fields/ZZZ_TEST_I__c.field-meta.xml
<CustomField>
    <fullName>ZZZ_TEST_I__c</fullName>
    <defaultValue>&apos;INFO&apos;</defaultValue>
    <label>ZZZ_TEST_I</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

modules/lgr/main/default/objects/lgr_LogLevels__c/fields/ZZZ_TEST_W__c.field-meta.xml
<CustomField>
    <fullName>ZZZ_TEST_W__c</fullName>
    <defaultValue>&apos;WARNING&apos;</defaultValue>
    <label>ZZZ_TEST_W</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

modules/lgr/main/default/classes/lgr_LoggerTest.cls
@isTest
private class lgr_LoggerTest {

    private class TestException extends Exception {}

    @TestSetup
    static void makeData(){
        lgr_LogLevels__c defaultSetting = new lgr_LogLevels__c(SetupOwnerId=UserInfo.getOrganizationId());
        defaultSetting.put('ZZZ_TEST_C__c', lgr_Logger.LogLevel.CRITICAL.name());
        defaultSetting.put('ZZZ_TEST_W__c', lgr_Logger.LogLevel.WARNING.name());
        defaultSetting.put('ZZZ_TEST_I__c', lgr_Logger.LogLevel.INFO.name());
        defaultSetting.put('ZZZ_TEST_D__c', lgr_Logger.LogLevel.DEBUG.name());
        insert defaultSetting;
    }

    @IsTest 
    static void testLogFields() {
        Test.startTest();
        DateTime beforeOccured = System.now().addSeconds(-1);
        lgr_Logger.log('ZZZ_TEST_C', 'methodB', 'Message C', 'Params C', 'Stack F', lgr_Logger.LogLevel.CRITICAL);
        DateTime afterOccured = System.now().addSeconds(1);
        Test.stopTest();
        assertLogFields(beforeOccured, afterOccured, 'ZZZ_TEST_C', 'methodB', 'Message C', 'Stack F', lgr_Logger.LogLevel.CRITICAL, 'Params C');
    }

    @IsTest 
    static void testLogException() { // ! this also tests the lgr_LogEvent__e platform-event-triggered flow, so be sure that is activated!
        Test.startTest();
        DateTime beforeOccured = System.now().addSeconds(-1);
        TestException e = new TestException('uh oh!');
        lgr_Logger.log(e, 'ZZZ_TEST_C', 'method1', 'params1');
        DateTime afterOccured = System.now().addSeconds(1);
        Test.stopTest();
        assertLogFields(beforeOccured, afterOccured, 'ZZZ_TEST_C', 'method1', 'uh oh!', e.getStackTraceString(), lgr_Logger.LogLevel.CRITICAL, 'params1');
    }

    @IsTest 
    static void testLogCritical() {
        Test.startTest();
        lgr_Logger.log('ZZZ_TEST_C', 'methodB', 'Message C', 'Params C', 'Stack F', lgr_Logger.LogLevel.CRITICAL);
        lgr_Logger.log('ZZZ_TEST_W', 'methodB', 'Message W', 'Params C', 'Stack F', lgr_Logger.LogLevel.CRITICAL);
        lgr_Logger.log('ZZZ_TEST_I', 'methodB', 'Message I', 'Params C', 'Stack F', lgr_Logger.LogLevel.CRITICAL);
        lgr_Logger.log('ZZZ_TEST_D', 'methodB', 'Message D', 'Params C', 'Stack F', lgr_Logger.LogLevel.CRITICAL);
        lgr_Logger.log('Not a class', 'methodB', 'Message X', 'Params C', 'Stack F', lgr_Logger.LogLevel.CRITICAL); // still should be logged since it is critical
        DateTime afterOccured = System.now().addSeconds(1);
        Test.stopTest();
        lgr_Log__c[] logs = [SELECT Id, Class__c FROM lgr_Log__c];
        System.assertEquals(5, logs.size(), 'all logs should have been created.');
    }

    @IsTest 
    static void testLogWarning() {
        Test.startTest();
        lgr_Logger.log('ZZZ_TEST_C', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.WARNING);
        lgr_Logger.log('ZZZ_TEST_W', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.WARNING);
        lgr_Logger.log('ZZZ_TEST_I', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.WARNING);
        lgr_Logger.log('ZZZ_TEST_D', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.WARNING);
        lgr_Logger.log('Not a class', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.WARNING);
        Test.stopTest();
        lgr_Log__c[] logs = [SELECT Id, Class__c FROM lgr_Log__c];
        System.assertEquals(3, logs.size());
        // make sure the correct logs were created
        for (lgr_Log__c log : logs) {
            System.assertNotEquals('ZZZ_TEST_C', log.Class__c);
            System.assertNotEquals('Not a class', log.Class__c);
        }
    }

    @IsTest 
    static void testLogInfo() {
        Test.startTest();
        lgr_Logger.log('ZZZ_TEST_C', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.INFO);
        lgr_Logger.log('ZZZ_TEST_W', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.INFO);
        lgr_Logger.log('ZZZ_TEST_I', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.INFO);
        lgr_Logger.log('ZZZ_TEST_D', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.INFO);
        lgr_Logger.log('Not a class', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.INFO);
        Test.stopTest();
        lgr_Log__c[] logs = [SELECT Id, Class__c FROM lgr_Log__c];
        System.assertEquals(2, logs.size());
        // make sure the correct logs were created
        for (lgr_Log__c log : logs) {
            System.assertNotEquals('ZZZ_TEST_C', log.Class__c);
            System.assertNotEquals('Not a class', log.Class__c);
            System.assertNotEquals('ZZZ_TEST_W', log.Class__c);
        }
    }

    @IsTest 
    static void testLogDebug() {
        Test.startTest();
        lgr_Logger.log('ZZZ_TEST_C', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.DEBUG);
        lgr_Logger.log('ZZZ_TEST_W', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.DEBUG);
        lgr_Logger.log('ZZZ_TEST_I', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.DEBUG);
        lgr_Logger.log('ZZZ_TEST_D', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.DEBUG);
        lgr_Logger.log('Not a class', 'methodB', 'Message A', 'Params C', 'Stack F', lgr_Logger.LogLevel.DEBUG);
        Test.stopTest();
        lgr_Log__c[] logs = [SELECT Id, Class__c FROM lgr_Log__c];
        System.assertEquals(1, logs.size());
        // make sure the correct logs were created
        System.assertEquals('ZZZ_TEST_D', logs[0].Class__c);
    }

    static void assertLogFields(DateTime beforeOccured, DateTime afterOccured, String className, String method, String message, String stackTrace, lgr_Logger.LogLevel logLevel, String params) {
        lgr_Log__c[] logs = [SELECT Class__c, Method__c, Parameters__c, Level__c, StackTrace__c, Message__c, Occured__c FROM lgr_Log__c];
        system.assertEquals(1, logs.size());
        lgr_Log__c log = logs[0];
        System.assertEquals(className, log.Class__c);
        System.assertEquals(method, log.Method__c);
        System.assertEquals(message, log.Message__c);
        System.assertEquals(stackTrace, log.StackTrace__c);
        System.assertEquals(logLevel.name(), log.Level__c);
        System.assertEquals(params, log.Parameters__c);
        System.assert(log.Occured__c < afterOccured && log.Occured__c > beforeOccured, 'Occured__c time is not accurate. log.Occured = ' + log.Occured__c + ', beforeOccured = ' + beforeOccured + ', afterOccured = ' + afterOccured);
    }
}